name: GitHub Release

on:
  push:
    tags:
      # "v" で始まる Tag 名の push だけをトリガーの対象にします (e.g., "v0.0.2")
      - "v*"

jobs:
  # Windows 用の job 定義
  build_on_win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: npm install
        run: npm install
      # - name: License Generator
      #   run: |
      #     npm install -g license-checker
      #     npm run licensegen
      - name: build application
        run: |
          echo ${{ secrets.SHAPANET_AWS_CREDENTIALS }} | base64 -d > public/credentials.json
          npm run electron:release --win
